POST localhost:8080/direction/add
Content-Type: application/json

{
  "name": "backend",
  "description": "about from this"
}

###

POST localhost:8080/user
Content-Type: application/json

{
  "name": "Alex",
  "username": "Test",
  "password": "test"
}


###
POST localhost:8080/direction/add
Content-Type: application/json

{
"name": "HR"

}

###
POST localhost:8080/direction/add
Content-Type: application/json

{
  "name": "frontend",
  "description": "from frontend developer"
}